setup:
  name: 'Setup'
  stage: .pre
  script:
    - java -version
    - mvn --version
    - echo CI_SERVER_URL = $CI_SERVER_URL
    - echo CI_REPOSITORY_URL = $CI_REPOSITORY_URL
    - echo CI_MERGE_REQUEST_IID = $CI_MERGE_REQUEST_IID
    - echo CI_BUILDS_DIR = $CI_BUILDS_DIR
    - echo CI_PROJECT_DIR = $CI_PROJECT_DIR
    - echo CI_PROJECT_ID = $CI_PROJECT_ID
    - echo CI_COMMIT_SHA = $CI_COMMIT_SHA

build:
  stage: build
  script:
    - mvn -V --color always -ntp clean verify --file pom.xml '-Dgpg.skip'

test:
  image: docker.io://uhafner/autograding-github-action:3.10.0
  stage: test
  script:
    - echo "Hello World!"
