jenkins:
  authorizationStrategy: "loggedInUsersCanDoAnything"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
    - "hudson.diagnosis.ReverseProxySetupMonitor"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: NORMAL
  nodes:
    - permanent:
        labelString: "docker linux agent java jdk21 java21"
        launcher:
          ssh:
            credentialsId: "jenkins-ssh-agent-private-key"
            host: "java-agent"
            port: 22
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        name: "java-agent"
        nodeDescription: "Jenkins Docker Agent with Java 21 and Maven"
        numExecutors: 1
        remoteFS: "/home/jenkins/agent"
        retentionStrategy: "always"
  numExecutors: 0
  primaryView:
    list:
      columns:
        - "status"
        - "weather"
        - "jobName"
        - "gitBranchSpecifierColumn"
        - "lastSuccess"
        - "lastFailure"
        - "lastDuration"
        - coverageTotalsColumn:
            columnName: "Line Coverage"
            metric: LINE
        - coverageTotalsColumn:
            columnName: "Branch Coverage"
            metric: BRANCH
        - "issueTotalsColumn"
        - "buildButton"
      includeRegex: ".*"
      name: "List View"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
  slaveAgentPort: 50000
  systemMessage: "<h1>Java and Maven Showcase</h1>"
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - list:
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "gitBranchSpecifierColumn"
          - "lastSuccess"
          - "lastFailure"
          - "lastDuration"
          - coverageTotalsColumn:
              columnName: "Line Coverage"
              metric: LINE
          - coverageTotalsColumn:
              columnName: "Branch Coverage"
              metric: BRANCH
          - "issueTotalsColumn"
          - "buildButton"
        includeRegex: ".*"
        name: "List View"
    - dashboard:
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastSuccess"
          - "lastFailure"
          - "lastDuration"
          - coverageTotalsColumn:
              columnName: "Line Coverage"
              metric: LINE
          - coverageTotalsColumn:
              columnName: "Branch Coverage"
              metric: BRANCH
          - "issueTotalsColumn"
          - "buildButton"
        includeStdJobList: true
        includeRegex: ".*"
        leftPortlets:
          - issuesChartPortlet:
              height: 600
              name: "Static analysis issues chart"
        name: "Dashboard View"
        rightPortlets:
          - issuesTablePortlet:
              name: "Static analysis issues per tool and job"
              showIcons: true
  viewsTabBar: "standard"

appearance:
  locale:
    ignoreAcceptLanguage: true
    systemLocale: "USE_BROWSER_LOCALE"
  prism:
    theme: PRISM

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              description: "Private SSH key for Jenkins agent"
              id: "jenkins-ssh-agent-private-key"
              privateKeySource:
                directEntry:
                  privateKey: ${readFile:/ssh-dir/jenkins_agent_ed}
              scope: SYSTEM
              username: "jenkins"
unclassified:
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  location:
    adminAddress: "Address not configured <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
  pollSCM:
    pollingThreadCount: 10

tool:
  git:
    installations:
      - home: "git"
        name: "git-default"
  maven:
    installations:
      - home: "/opt/maven"
        name: "mvn-default"
  pipelineMaven:
    publisherOptions:
      - jacocoPublisher:
          disabled: true
      - junitPublisher:
          disabled: true
          healthScaleFactor: 1.0
    triggerDownstreamUponResultAborted: false
    triggerDownstreamUponResultFailure: false
    triggerDownstreamUponResultNotBuilt: false
    triggerDownstreamUponResultSuccess: true
    triggerDownstreamUponResultUnstable: false
