@startuml

skinparam activity {
  BackgroundColor #eaeaea
  BorderColor #a0a0a0
  BorderColor black
  ArrowColor black
  ArrowThickness 2
  FontName Arial Unicode MS
  FontSize 20
}

sprite $rake [16x19/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

skinparam ArrowColor black
skinparam ArrowThickness 2

skinparam activityDiamondBackgroundColor #f5f5f5
skinparam activityDiamondFontColor #black
skinparam activityDiamondBorderColor black
skinparam activityDiamondFont Arial Unicode MS
skinparam activityArrowFontSize 20
skinparam activityArrowFont Arial Unicode MS

|Partition 1|
start
repeat
:Erste Aktion;
    if( Frage? ) then ([true]\t)
        :Alternative Links;
    else (\t[false])
        :Alternative Rechts;
    endif
|Partition 2|
    :Zweite Aktion;
    repeat while () is ( [Bedingung 1])
    -> [Bedingung 2];
    :Weitere Aktion;
    :Weitere Aktivität <$rake>;
        :Objekt; <<task>>
|Partition 1|
fork
:Parallele Aktion 1;
fork again
:Parallele Aktion 2;
fork end
stop
@enduml
