@startuml

skinparam package {
  BackgroundColor #efefef
  BorderColor #a0a0a0
  BackgroundColor<<Main>> gold
  BorderColor black
  ArrowColor black
  FontName Arial Unicode MS
  FontSize 20
}

skinparam class {
  BackgroundColor #white
  BorderColor #f4f4f4
  BackgroundColor<<Main>> gold
  BorderColor black
  ArrowColor black
  FontName Arial Unicode MS
  FontSize 20
}

skinparam note {
  BackgroundColor LightBlue
  BorderColor #a0a0a0
  FontName Arial
  FontSize 14
  FontColor black
  RoundCorner 15
  LineType solid
}

skinparam classFontSize 24
skinparam classAttributeIconSize 0
skinparam defaultFontSize 20

skinparam ArrowColor black
skinparam ArrowThickness 2

hide circle

package java.util {
    class Observable {
        - changed: boolean
        +registerObserver(o: Observer)
        +unregisterObserver(o: Observer)
        #notifyObservers()
    }

    interface Observer <<interface>> {
        +update() {abstract}
    }
}

class ConcreteObservable {
    -concreteState: State
    +getState(): State
    +setState(s: State)
}

Observable <|-- ConcreteObservable

hide interface fields

abstract class AbstractObserver < T extends Observer >  {
    +update()
    #handleUpdate(o: Observer) {abstract}
}

class ConcreteObserver {
    #handleUpdate(o: Observer)
}

class StringUtils {
    +isEmpty(value: String) {static}
}

Observable o- Observer : \t\t

Observer <|.. AbstractObserver
AbstractObserver <|-- ConcreteObserver : <<bind>> \n<T -> ConcreteObserver>
ConcreteObservable <-left- ConcreteObserver : \t\t
ConcreteObservable .down.> StringUtils : <<use>>

' Notes

note "Package" as Package
note "Subpackage" as Subpackage
note "Klasse" as Class
note "Interface" as Interface
note "Vererbung" as Vererbung
note "Implementierung" as Implementierung
note "gerichtete Assoziation" as Assoziation
note "generischen Typ binden" as Generics
note "gerichtete Abhängigkeit:\n<<use>> benutzt\n<<create>> erzeugt\n<<call>> Aufruf" as Dependency
note "Aggregation" as Aggregation

java .right[#lightblue,dotted]. Package
util .down[#lightblue,dotted]. Subpackage
Observable .up. Class
Observable .[#lightblue,dotted]. Vererbung
ConcreteObservable .up[#lightblue,dotted]. Vererbung
Observer .up. Interface

Observer .up[#lightblue,dotted]. Aggregation
Aggregation .up[#lightblue,dotted]. Observable

Observer .down[#lightblue,dotted]. Implementierung
AbstractObserver .up[#lightblue,dotted]. Implementierung

ConcreteObserver .down[#lightblue,dotted]. Assoziation
ConcreteObservable .down[#lightblue,dotted]. Assoziation

ConcreteObserver .up[#lightblue,dotted]. Generics
AbstractObserver .down[#lightblue,dotted]. Generics

ConcreteObservable .[#lightblue,dotted]. Dependency
StringUtils .up[#lightblue,dotted]. Dependency

note right of ConcreteObservable::concreteState
  Objektvariable
  vom Typ <i>State</i>
end note

note right of ConcreteObservable::getState
  Methode mit
  Rückgabetyp <i>State</i>
end note

note right of ConcreteObservable::setState
  Methode mit
  Parametertyp <i>State</i>
end note

note right of StringUtils::isEmpty
  statische Methode
end note

note as floating
  <u><b>Sichtbarkeiten</b></u>

    + public
    # protected
    ~ package private
    - private
end note

note as notes
  <u><b>Anmerkungen</b></u>

    Die blauen Boxen und Linien
    sind nur Anmerkungen. In
    eigenen Diagrammen werden
    sie nicht verwendet.
end note

@enduml
