@startuml

skinparam component {
  BackgroundColor #f8f8f8
  BorderColor #a0a0a0
  BackgroundColor<<Main>> #FFFF00
  BorderColor black
  FontName Arial Unicode MS
  FontSize 20
  ArrowFontName Arial Unicode MS
  ArrowFontSize 18
}

skinparam classFontSize 24
skinparam classAttributeIconSize 0
skinparam defaultFontSize 20

skinparam ArrowColor black
skinparam ArrowThickness 2

skinparam note {
  BackgroundColor LightBlue
  BorderColor #a0a0a0
  FontName Arial
  FontSize 14
  FontColor black
  RoundCorner 15
  LineType solid
}

hide circle

skinparam componentStyle uml2

component "Anwendung" <<component>> as anwendung {
    artifact anwendung-1.0.0.war <<artifact>> as war {
    }
}

component "Fachkomponente" <<component>> as fachkomponente {
    artifact fachlogik-1.0.0.jar <<artifact>> as jar {
    }
}

component " org.apache.commons:commons-lang3      " <<component>> as library {
    artifact commons-lang3-3.12.jar <<artifact>> as lang {
    }
}

anwendung .up.> library : " <<use>>"
circle "\t         Fassade " as fassade
anwendung ..> fassade : " <<call>>"

note "Artefakt" as artefact
note "Komponente" as component
note "Schnittstelle" as schnittstelle
note "Implementierung\neiner Schnittstelle" as Implementierung
note "Aufruf einer\nSchnittstelle" as Use
note "gerichtete Abhängigkeit\nohne Angabe Interface" as Dependency


fassade -up- fachkomponente

anwendung .[#blue,dotted]down. Use
fassade .[#blue,dotted]up. Use

fassade .[#blue,dotted]left. schnittstelle
library .[#blue,dotted]up. component
lang .[#blue,dotted]down. artefact

fassade .[#blue,dotted]down. Implementierung
fachkomponente .[#blue,dotted]right. Implementierung

anwendung .up[#blue,dotted]. Dependency
library .down[#blue,dotted]. Dependency

note as notes
  <u><b>Anmerkungen</b></u>

    Die blauen Boxen und gepunkteten
    Linien sind nur Anmerkungen. In
    eigenen Diagrammen werden sie
    nicht verwendet.
end note

notes .[hidden]up. anwendung

@enduml
