@startuml

skinparam componentStyle uml2
skinparam FontName Arial Black
skinparam classFontName Arial
skinparam classAttributeIconSize 0
skinparam defaultFontSize 20
skinparam classFontSize 24
skinparam componentStyle uml2
skinparam ArrowColor black

skinparam node {
  BackgroundColor #f4f4f4
  BorderColor #a0a0a0
  BackgroundColor<<Main>> gold
  BorderColor black
}

skinparam artifact {
  BackgroundColor #e4e4e4
  BorderColor #a0a0a0
  ArrowColor black
  FontName  Arial Unicode MS
  FontSize 20
  StereotypeFontSize 14
}


node ":MacBook" <<device>> {
    node ":macOS Monterey" <<execution environment>>  {
        node ":Safari 15.4" <<execution environment>>  {
            artifact ECharts.JS <<artifact>> as EI
            artifact DataTables.JS <<artifact>> as DI
            artifact ClientModel.JS <<artifact>> as P
        }
    }
}


P ..> EI
P ..> DI

node ":Server" <<device>> {
    node ":Jetty 9.4.45" <<execution environment>>  {
        artifact Warnings <<artifact>> as W
        artifact Jenkins.Core <<artifact>> as C
    }
}

C <. W

":Server" -down- ":MacBook" : "  <<Socket>>"

note "Artefakt" as artifact
note "Kommunikationspfad\nmit Protokoll" as channel
note "Device" as device
note "Execution Environment" as env

":Server" .up. device
":Safari 15.4" .down. env

":Server" .. channel
":MacBook" .. channel

W .right. artifact


@enduml
