@startuml

skinparam actor {
  BackgroundColor #f4f4f4
  BorderColor #a0a0a0
  BorderColor black
  ArrowColor black
  FontName Arial Unicode MS
  FontSize 20
}

skinparam usecase {
  BackgroundColor #f4f4f4
  BorderColor #a0a0a0
  BorderColor black
  ArrowColor black
  FontName Arial Unicode MS
  FontSize 20
}

skinparam ArrowColor black
skinparam ArrowThickness 2

left to right direction

:Akteur:
:Abgeleiteter Akteur:

:Akteur: <|- :Abgeleiteter Akteur: :\t\t\t

rectangle Gruppierung #e4e4e4 {
    (Anwendungsfall) -up- Akteur
    (Eingebundener\nAnwendungsfall) <. (Anwendungsfall) : \t\t         <<Include>>
    :Abgeleiteter Akteur: -- (Beschränkter\nAnwendungsfall)
}

@enduml
