name: 'Link Checker'

on: push

jobs:
  check-markdown-links:
    name: 'Check Markdown links'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: 'no'
          config-file: '.github/check-md-links.json'
