name: Label Checker
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  enforce-labels:
    name: 'Enforce PR labels'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "bug,feature,enhancement,breaking,tests,documentation,internal,dependencies"
          message: "Maintainer needs to assign at least one label before merge"
