name: GitHub Actions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -V -ntp clean verify --file pom.xml '-Dgpg.skip'

  coverage:

    runs-on: [ubuntu-latest]
    name: coverage on Ubuntu

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Coverage with JaCoCo
        run: mvn -V -ntp clean verify jacoco:prepare-agent test integration-test jacoco:report --file pom.xml '-Dgpg.skip'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
