name: 'Quality Monitor Comment'

on:
  workflow_run:
    workflows: ["Quality Monitor Build"]
    types: [completed]
permissions:
  contents: read
  pull-requests: write

jobs:
  comment:

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: [ubuntu-latest]

    steps:
      - name: Artefakt laden
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: quality-reports
      - name: Load Quality Gates JSON
        id: quality-gates
        run: echo "json=$(jq -c . .github/quality-gates.json)" >> "$GITHUB_OUTPUT"
      - name: Load Quality Monitor Config
        id: quality-monitor
        run: echo "json=$(jq -c . .github/quality-monitor.json)" >> "$GITHUB_OUTPUT"
      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@delete-comments
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          config: ${{ steps.quality-monitor.outputs.json }}
          quality-gates: ${{ steps.quality-gates.outputs.json }}
          pr-number: ${{ steps.pr.outputs.number }}
          comments-strategy: 'UPDATE'
          show-headers: true
          title-metric: 'tests-success-rate'
