name: 'Quality Monitor PR'

on:
  pull_request:

jobs:
  build:

    runs-on: [ubuntu-latest]
    name: Monitor project quality

    steps:
      - name: 'Checkout merge request'
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha || github.event.pull_request.head.sha }}"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Cache the NVD database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check
      - name: Build with Maven
        env:
          BROWSER: chrome-container
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -V --color always -ntp clean verify -Ppit -Pci -Powasp | tee maven.log
      - name: Extract pull request number
        uses: jwalton/gh-find-current-pr@v1
        id: pr
      - name: Load Quality Gates JSON
        id: quality-gates
        run: echo "json=$(jq -c . .github/quality-gates.json)" >> "$GITHUB_OUTPUT"
      - name: Load Quality Monitor Config
        id: quality-monitor
        run: echo "json=$(jq -c . .github/quality-monitor.json)" >> "$GITHUB_OUTPUT"
      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@delete-comments
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          config: ${{ steps.quality-monitor.outputs.json }}
          quality-gates: ${{ steps.quality-gates.outputs.json }}
          pr-number: ${{ steps.pr.outputs.number }}
          comments-strategy: 'UPDATE'
          show-headers: true
          title-metric: 'tests-success-rate'
