name: 'Quality Monitor'

on:
  pull_request:

jobs:
  build:

    runs-on: [ubuntu-latest]
    name: Create quality reports

    steps:
      - name: 'Checkout merge request'
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Cache the NVD database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check
      - name: Build with Maven
        env:
          BROWSER: chrome-container
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -V --color always -ntp clean verify -Ppit -Pci -Powasp | tee target/maven.log
      - name: Upload Quality Reports
        uses: actions/upload-artifact@v5
        with:
          name: quality-reports
          path: |
            **/target/**/*.json
            **/target/**/*.xml
            **/target/**/*.log

