name: 'Quality Monitor Comment'

on:
  workflow_run:
    workflows: [ "Quality Monitor Build" ]
    types: [ completed ]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  comment:

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    name: Comment

    steps:
      - name: Artefakt laden
        uses: dawidd6/action-download-artifact@v11
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: file
