name: 'Quality Monitor PR'

on:
  pull_request_target:

jobs:
  build:

    runs-on: [ubuntu-latest]
    name: Monitor project quality

    steps:
      - name: 'Checkout merge request'
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha || github.event.pull_request.head.sha }}"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Cache the NVD database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check
      - name: Build with Maven
        env:
          BROWSER: chrome-container
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -V --color always -ntp clean verify -Ppit -Pci -Powasp | tee maven.log
      - name: Extract pull request number
        uses: jwalton/gh-find-current-pr@v1
        id: pr
      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@delete-comments
        with:
          pr-number: ${{ steps.pr.outputs.number }}
          show-headers: true
          comments-strategy: 'REMOVE'
          title-metric: 'tests-success-rate'
          quality-gates: >
            {
              "qualityGates": [
                {
                  "metric": "tests-success-rate",
                  "name": "Tests Success Rate",
                  "threshold": 100.0,
                  "criticality": "FAILURE"
                },
                {
                  "metric": "line",
                  "threshold": 80.0,
                  "criticality": "UNSTABLE"
                },
                {
                  "metric": "branch",
                  "threshold": 80.0,
                  "criticality": "UNSTABLE"
                },
                {
                  "metric": "test-strength",
                  "threshold": 90.0,
                  "criticality": "UNSTABLE"
                },
                {
                  "metric": "bugs",
                  "threshold": 0.0,
                  "criticality": "FAILURE"
                },
                {
                  "metric": "style",
                  "threshold": 0.0,
                  "criticality": "UNSTABLE"
                }
              ]
            }
          config: >
            {
              "tests": {
                "name": "Tests",
                "tools": [
                  {
                    "id": "junit",
                    "name": "Unit Tests",
                    "pattern": "**/target/*-reports/TEST*util*.xml"
                  },
                  {
                    "id": "junit",
                    "icon": "no_entry",
                    "name": "Architecture Tests",
                    "pattern": "**/target/surefire-reports/TEST*archunit*.xml"
                  }
                ]
              },
              "analysis": [
                {
                  "name": "Style",
                  "id": "style",
                  "tools": [
                    {
                      "id": "checkstyle",
                      "pattern": "**/target/**checkstyle-result.xml"
                    },
                    {
                      "id": "pmd",
                      "pattern": "**/target/pmd-*/pmd.xml"
                    }
                  ]
                },
                {
                  "name": "Bugs",
                  "id": "bugs",
                  "icon": "bug",
                  "tools": [
                    {
                      "id": "spotbugs",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/spotbugsXml.xml"
                    },
                    {
                      "id": "error-prone",
                      "pattern": "**/maven.log"
                    }
                  ]
                },
                {
                  "name": "API Problems",
                  "id": "api",
                  "icon": "no_entry_sign",
                  "tools": [
                    {
                      "id": "revapi",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/revapi-result.json"
                    }
                  ]
                },
                {
                  "name": "Vulnerabilities",
                  "id": "vulnerabilities",
                  "icon": "shield",
                  "tools": [
                    {
                      "icon": "shield",
                      "id": "owasp-dependency-check",
                      "icon": "shield",
                      "pattern": "**/target/dependency-check-report.json"                    
                    }
                  ]
                }
              ],
              "coverage": [
                {
                  "name": "Code Coverage",
                  "tools": [
                    {
                      "id": "jacoco",
                      "metric": "line",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/site/jacoco/jacoco.xml"
                    },
                    {
                      "id": "jacoco",
                      "metric": "branch",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/site/jacoco/jacoco.xml"
                    }
                  ]
                },
                {
                  "name": "Mutation Coverage",
                  "tools": [
                    {
                      "id": "pit",
                      "metric": "mutation",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/pit-reports/mutations.xml"
                    },
                    {
                      "id": "pit",
                      "metric": "test-strength",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/pit-reports/mutations.xml"
                    }
                  ]
                }
              ],
              "metrics": 
                {
                  "name": "Software Metrics",
                  "tools": [
                    {
                      "id": "metrics",
                      "pattern": "**/metrics/pmd.xml",
                      "metric": "CYCLOMATIC_COMPLEXITY"
                    },
                    {
                      "id": "metrics",
                      "pattern": "**/metrics/pmd.xml",
                      "metric": "COGNITIVE_COMPLEXITY"
                    },
                    {
                      "id": "metrics",
                      "pattern": "**/metrics/pmd.xml",
                      "metric": "NPATH_COMPLEXITY"
                    },
                    {
                      "id": "metrics",
                      "pattern": "**/metrics/pmd.xml",
                      "metric": "LOC"
                    },
                    {
                      "id": "metrics",
                      "pattern": "**/metrics/pmd.xml",
                      "metric": "NCSS"
                    },
                    {
                      "id": "metrics",
                      "pattern": "**/metrics/pmd.xml",
                      "metric": "COHESION"
                    },
                    {
                      "id": "metrics",
                      "pattern": "**/metrics/pmd.xml",
                      "metric": "WEIGHT_OF_CLASS"
                    }
                  ]
                }
            }
