name: 'Quality Monitor Comment'

needs: [ "Quality Monitor Build" ]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  comment:

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    name: Comment

    steps:
      - name: Artefakt laden
        uses: actions/download-artifact@v4
        with:
          name: file
