name: 'OpenRewrite'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:

    runs-on: ubuntu-latest
    name: Run open rewrite

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Run open-rewrite
        run: mvn -V --color always -ntp clean rewrite:run
